[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openssl"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["PORT=8080 BASE_PATH=/ pnpm --filter './artifacts/api-server' --filter './artifacts/precifica' run build"]

[start]
cmd = "pnpm run start"
